### ISSUE TITLE
[spike] Changes to support Mac?

### ISSUE THREAD

**Issue by jvarness** [theIYD/source-me#12]
[dev.to post for reference](https://dev.to/theiyd/source-me-24p)

Was just wondering what you were wanting from this. I ran the code on my Mac and everything seemed fine.

Are you just looking for someone to build an executable for Mac?

**Comment by theIYD** [comment]
Thanks for opening up the issue. 

I do not own a Mac machine and i wanted a maintainer to build Source Me for Macintosh systems. Would you mind if you could maintain Source me for Mac ?

**Comment by jvarness** [comment]
I'm looking into trying to package an executable for Mac right now. I'll let you know how it goes.

**Comment by theIYD** [comment]
Thanks alot brother. 

Can we talk on a socail messaging app like Hangouts ?

**Comment by jvarness** [comment]
Sure, jake.varness@gmail.com

**Comment by theIYD** [comment]
Thanks @jvarness

**Comment by MilenFrom** [comment]
Hi Fellas,

I built App for macOS, will be happy to help with something :)

If you'd like to add me on Google Hangouts, use the same username - milenfrom.

Here's the link for macOS - https://github.com/MilenFrom/source-me/releases/tag/0.2.1-macOS

**Comment by theIYD** [comment]
Nice to see ! 

I have not been working on the app for a long time due to my semesters. If you have any feature requests or ideas, ping me on Google Hangouts at dargahidrees@gmail.com

Thanks.
