### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by ronan18** [theIYD/source-me#2]
source-me does not work with macOS Sierra 10.12.6.

**Comment by theIYD** [comment]
It does not work only on Sierra or on all versions ? 

What's the error ? 
Screenshot might be helpful.

**Comment by ronan18** [comment]
<img width="1000" alt="screen shot 2017-08-20 at 6 46 29 pm" src="https://user-images.githubusercontent.com/17938131/29499908-f14a2ec2-85d7-11e7-9504-d3ad212b6fea.png">

**Comment by ronan18** [comment]
I only have a mac with Sierra 10.12.6.

**Comment by ronan18** [comment]
I cloned the repo to my computer and ran it and i got this error: 
<img width="890" alt="screen shot 2017-08-20 at 6 52 23 pm" src="https://user-images.githubusercontent.com/17938131/29499953-d30de542-85d8-11e7-9b81-7f03fc0cf679.png">

**Comment by theIYD** [comment]
Okay, 

I will look into this problem and try to fix as soon as possible. 

Thanks for the screenshot and reports.

**Comment by ronan18** [comment]
thank you!

**Comment by ronan18** [comment]
I created a pull request that fixes the problem. I figured out that you were using a .icns file instead of a .png file for the tray icon.

**Comment by theIYD** [comment]
I will look into it very soon. The fix will be pushed very soon ! 

Thank you very much.

**Comment by theIYD** [comment]
The fix by @Rosho123 has been merged.

**Comment by Pustur** [comment]
@theIYD: The fix was merged on August 21st but the latest release is from August 19th, so i can't get the application to work on my mac, could you publish the latest release please?

Thanks :)

**Comment by theIYD** [comment]
@Pustur Due to college, i am not able to work on source-me. Will surely release a build on this weekend. 

Thanks for your interest in my application.
