### ISSUE TITLE
Tray Icon Mac

### ISSUE THREAD

**Issue by ronan18** [theIYD/source-me#4]
<img width="258" alt="screen shot 2017-08-22 at 8 00 15 am" src="https://user-images.githubusercontent.com/17938131/29572091-0f26cb10-8710-11e7-9082-da17ad6f2b85.png">

On a 27" iMac the icon is stretched out of proportion.

**Comment by theIYD** [comment]
Thanks for the issue. 

**I'll be testing the app on a mac machine very soon and fix all the issues.**

**Comment by ronan18** [comment]
ok thank you! would you like me to keep reporting them?

**Comment by theIYD** [comment]
Issues are welcomed. More the issues, more things to be fixed and app will become more and more stable.

**Comment by theIYD** [comment]
**Update:**

I am **not** able to get a Mac Machine and test the application. @Rosho123 Could you please handle the app over mac platform and make pull requests to fix the issues on mac ? 

_Hope you reply very soon._ 

Thanks

**Comment by ronan18** [comment]
OK will do, I am kinda busy lately but when I get a chance I will.

**Comment by theIYD** [comment]
No hurries man. The application will not be abandoned. 😉
