### ISSUE TITLE
Image compressor - not saved

### ISSUE THREAD

**Issue by benceHornyak** [theIYD/source-me#8]
### Image compressor component: 
If I chose an image and cancel before saving it is says: "The compressed image was saved"
But I have not saved it.

#### Reproduction:
Go to Image Compress, choose an image, open it and before save cancel the dialog.

**Release**: 0.2.1

**Comment by theIYD** [comment]
Currently, it is fixed by not showing the message, but will be fixed in future releases

https://github.com/theIYD/source-me/commit/51d6962768a01ba9040102426f62b3e61103c3c0
